trigger:
- feature/add_azure_pipelines

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Compile
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '11'
        jdkArchitectureOption: 'x64'
        goals: 'clean compile'
  - job: Install_skencli
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: pip install --upgrade skencli
  - job: Run_skencli
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: ~/local/bin/skencli
