trigger:
- feature/add_azure_pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  displayName: Compile
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    goals: 'clean compile'
- task: Bash@3
  displayName: Install_skencli
  inputs:
    targetType: 'inline'
    script: pip install --upgrade skencli
- task: Bash@3
  displayName: Run_skencli
  inputs:
    targetType: 'inline'
    script: /usr/local/bin/skencli
